allotment_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('allotments/', include('allotments.urls')),
]

allotments/urls.py
from django.urls import path
from . import views


app_name = 'allotments'

urlpatterns = [
    path('new', views.new_allotment, name='new-allotment'),
    path('view', views.display_allotements, name='allotments'),
]

allotments/models.py
from django.db import models
from allotment_system.settings import AUTH_USER_MODEL
# Create your models here.
class Branch(models.Model):
    branch_code=models.CharField(max_length=50,primary_key=True)
    branch_name=models.CharField(max_length=50)
    hod=models.ForeignKey(AUTH_USER_MODEL,on_delete=models.DO_NOTHING,null=True,blank=True,related_name='branch')
    def __str__(self):
        return self.branch_name
    class Meta:
        verbose_name_plural='Branches'


class Program(models.Model):
    program_name=models.CharField(max_length=50)
    def __str__(self):
        return self.program_name

class Batch(models.Model):
    program=models.ForeignKey(Program,on_delete=models.DO_NOTHING,related_name='batches',null=True,blank=True)
    batch_name=models.CharField(max_length=50)
    def __str__(self):
        return self.batch_name
    class Meta:
        verbose_name_plural='Batches'
class Student(models.Model):
    name=models.CharField(max_length=50)
    rollno=models.CharField(max_length=50,primary_key=True)
    branch=models.ForeignKey(Branch,on_delete=models.DO_NOTHING,related_name='students')
    batch=models.ForeignKey(Batch,on_delete=models.DO_NOTHING,related_name='students')
    program=models.ForeignKey(Program,on_delete=models.DO_NOTHING,related_name='students')
    minor_branch=models.ForeignKey(Branch,on_delete=models.DO_NOTHING,related_name='minor_branch',null=True,blank=True)
    def __str__(self):
        return self.rollno+" ( "+self.name+" )"

class Subject_type(models.Model):
    type=models.CharField(max_length=50)
    max_marks=models.IntegerField()
    def __str__(self):
        return self.type

class Regulation(models.Model):
    regulation_name=models.CharField(max_length=50,primary_key=True)
    def __str__(self):
        return self.regulation_name

class Subject(models.Model):
    subject_name=models.CharField(max_length=150)
    subject_code=models.CharField(max_length=50)
    subject_type=models.ForeignKey(Subject_type,on_delete=models.DO_NOTHING,related_name='subjects')
    regulation=models.ForeignKey(Regulation,on_delete=models.DO_NOTHING,related_name='subjects')
    program=models.ForeignKey(Program,on_delete=models.DO_NOTHING,related_name='subjects')
    branch=models.ForeignKey(Branch,on_delete=models.DO_NOTHING,related_name='subjects')
    year=models.IntegerField()
    semester=models.IntegerField()
    credits=models.DecimalField(max_digits=3,decimal_places=1)
    def __str__(self):
        return self.subject_name+" ( "+self.branch.branch_name+" )"
    class Meta:
        unique_together = ('subject_code', 'branch')

class Allotment(models.Model):
    branch=models.ForeignKey(Branch,on_delete=models.DO_NOTHING,related_name='allotments')
    subject=models.ForeignKey(Subject,on_delete=models.DO_NOTHING,related_name='allotments')
    faculty=models.ForeignKey(AUTH_USER_MODEL,on_delete=models.DO_NOTHING,related_name='allotments')
    batch=models.ForeignKey(Batch,on_delete=models.DO_NOTHING,related_name='allotments')
    def __str__(self):
        return self.faculty.first_name+" "+self.faculty.last_name+" ( "+self.subject.subject_name+" )"
    class Meta:
        unique_together = ('subject', 'faculty','batch')

class AcademicYear(models.Model):
    year=models.CharField(max_length=50)
    batch=models.ForeignKey(Batch,on_delete=models.DO_NOTHING,related_name='academic_years')
    
    def __str__(self):
        return self.year

allotments/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib import messages
from allotments.models import *
from user.models import User
from django.urls import reverse
# Create your views here.
def new_allotment(request):
    if request.method=='GET':
        try:
            return render(request,'NewAllotment.html',{'subjects':Subject.objects.all(),'faculties':User.objects.filter(is_faculty=True),'branches':Branch.objects.all(),'batches':Batch.objects.all(),'programs':Program.objects.all(),'regulations':Regulation.objects.all()})
        except Exception as e:
            print(e)
            return HttpResponse("Something went wrong")
    elif request.method=='POST':
        try:
            program=request.POST.get('program')
            branch = request.POST.get('branch')
            batch = request.POST.get('batch')
            faculty = request.POST.get('faculty')
            subject = request.POST.get('subject')
            year = request.POST.get('year')
            semester = request.POST.get('semester')
            faculty_branch=request.POST.get('faculty_branch')
            if Allotment.objects.filter(branch=Branch.objects.get(branch_code=branch),batch=Batch.objects.get(id=batch),subject=Subject.objects.get(id=subject),faculty=User.objects.get(id=faculty)).first():
                messages.error(request, "Allotment Already Exists")
            else:
                Allotment.objects.create(branch=Branch.objects.get(branch_code=branch),batch=Batch.objects.get(id=batch),faculty=User.objects.get(id=faculty),subject=Subject.objects.get(id=subject))
                messages.success(request, "Allotment Saved")
            # branch=Branch.objects.get(branch_code=branch).branch_code
            return render(request,'NewAllotment.html',{'subjects':Subject.objects.all(),'faculties':User.objects.filter(is_faculty=True),'branches':Branch.objects.all(),'batches':Batch.objects.all(),'branch':branch,'batch':batch,'year':year,'semester':semester,'faculty_branch':faculty_branch,'programs':Program.objects.all(),'program':program})
        except Exception as e:
            print(e)
            return HttpResponse("Something went wrong")
        
def display_allotements(request):
    if request.method=='GET':
        try:
            branches = Branch.objects.all()
            faculties = User.objects.filter(is_faculty=True)
            # batch = Batch.objects.order_by("batch_name")
            # starting_year = batch[0].batch_name.split("-")[0]
            # ending_year = batch[len(batch)-1].batch_name.split("-")[1]
            # academic_years = []
            # for i in range(int(starting_year),int(ending_year)+1):
            #     academic_years.append(str(i)+"-"+str(i+1))
            programs = Program.objects.all()
            academic_years = AcademicYear.objects.order_by("year").values_list('year',flat=True).distinct()
            return render(request,'AllotmentFilter.html',{'branches':branches,'faculties':faculties,'academic_years':academic_years,'programs':programs})
        except Exception as e:
            print(e)
            return HttpResponse("Something went wrong")
    if request.method == 'POST':
        try:
            if request.POST.get('submit')=='faculty':
                filter_kwargs = {}
                branch = request.POST.get('branch')
                faculty = request.POST.get('faculty')
                academic_year = request.POST.get('academic_year')
                semester = request.POST.get('semester')
                print(branch,faculty,academic_year,semester)
                # starting_year = academic_year.split("-")[0]
                # for i in range(4):
                #     year=str(int(starting_year)-i)
                #     batch=Batch.objects.get(batch_name=year+"-"+str(int(year)+4))
                if branch:
                    filter_kwargs['branch__branch_code'] = branch
                if semester:
                    filter_kwargs['subject__semester'] = semester
                if academic_year:
                    batches = AcademicYear.objects.filter(year=academic_year).values_list('batch',flat=True)
                    print(batches)
                    filter_kwargs['batch__id__in'] = batches
                # if request.POST.get('branch'):
                #     branch = Branch.objects.get(branch_code=request.POST.get('branch'))
                #     filter_kwargs['branch__branch_code'] = request.POST.get('branch')
                if request.POST.get('faculty'):
                    faculty = User.objects.get(id=request.POST.get('faculty'))
                    if not branch:
                        branch = Branch.objects.get(branch_code=faculty.faculty_branch.branch_code)
                    else:
                        branch = Branch.objects.get(branch_code=branch)
                    filter_kwargs['faculty__id'] = request.POST.get('faculty')
                    allotments=Allotment.objects.filter(**filter_kwargs).select_related('subject','batch','branch','faculty')
                    return render(request,'Allotments.html',{'allotments':allotments,'branch':branch,'faculty':faculty,'type':'faculty'})
                
                else:
                    messages.error(request, "Please select a faculty")
                    return HttpResponseRedirect(reverse('allotments:display_allotements'))
            elif request.POST.get('submit')=='class':
                filter_kwargs = {}
                program = request.POST.get('program')
                academic_year = request.POST.get('academic_year')
                year=request.POST.get('year')
                branch = request.POST.get('branch')
                semester = request.POST.get('semester')
                print(branch,academic_year,semester)
                # starting_year = academic_year.split("-")[0]
                # for i in range(4):
                #     year=str(int(starting_year)-i)
                #     batch=Batch.objects.get(batch_name=year+"-"+str(int(year)+4))
                if program:
                    filter_kwargs['batch__program__id'] = program
                if branch:
                    filter_kwargs['branch__branch_code'] = branch
                if year:
                    filter_kwargs['subject__year'] = year
                if semester:
                    filter_kwargs['subject__semester'] = semester
                if academic_year:
                    batches = AcademicYear.objects.filter(year=academic_year).values_list('batch',flat=True)
                    print(batches)
                    filter_kwargs['batch__id__in'] = batches
                # if request.POST.get('branch'):
                #     branch = Branch.objects.get(branch_code=request.POST.get('branch'))
                #     filter_kwargs['branch__branch_code'] = request.POST.get('branch')
                allotments=Allotment.objects.filter(**filter_kwargs).select_related('subject','batch','branch','faculty')
                return render(request,'Allotments.html',{'allotments':allotments,'branch':branch,'type':'class'})
        except Exception as e:
            print(e)
            return HttpResponse("Something went wrong")

allotments/templates/AllotmentFilter.html
{% load static %}
<html>

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\components.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script> -->

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <link rel="stylesheet" href="{% static 'css\admincss1.css' %}">
    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets\vendors\css\vendors.min.css'%}">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\bootstrap-extended.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\colors.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\components.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\themes\dark-layout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\themes\bordered-layout.css'%}">

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css"
        href="{% static 'app-assets\css\core\menu\menu-types\horizontal-menu.css' %} ">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\plugins\forms\form-validation.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\pages\page-auth.css' %}">
    <!-- END: Page CSS-->
    <script src="{% static 'app-assets\js\core\adminjs.js' %}"></script>
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css\admincss1.css' %}"> -->
    <style>
        .select2-results__option {
            color: black;
        }
    </style>
</head>

<body>
    <div class="topnav" id="myTopnav" class="show">
        <a href="{% url 'allotments:allotments' %}" class="active">Allotments</a>
        <a href="{% url 'allotments:new-allotment' %}">New Allotment</a>

        <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
    </div>
    <br /><br />
    <form action="{% url 'allotments:allotments'%}" method="post">
        {% csrf_token %}
        <div class="card m-auto" style="width: 80%;">
            <!-- <a href="">See All Allotments</a> -->
            <div class="card-body row">
                <div class="col-md-6">
                    <label>Academic Year</label>
                    <div class="select-style">
                
                        <select id="Academic-Year" name="academic_year" class="select-style">
                            <option value="Academic-Year" disabled>-- Academic Year --
                            </option>
                            {% for year in academic_years %}
                            <option value="{{year}}">{{year}}
                            </option>
                            {% endfor %}
                        </select>
                    </div><br>
                </div>
                <div class="col-md-6">
                    <br />
                    <label>Semester</label>
                    <div class="select-style">
                
                        <select id="Semester" name="semester">
                            <option value="Semester" {% if semester %} {% else %} selected {% endif %} disabled>--
                                Semester --</option>
                            <option value="1" {% ifequal semester "1" %} selected {% endifequal %}>1 Sem</option>
                            <option value="2" {% ifequal semester "2" %} selected {% endifequal %}>2 Sem</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <label>Branch</label>
                    <div class="select-style">

                        <select id="Branch" name="branch" class="select-style">
                            <option value="Branch" {% if branch %} {% else %} selected {% endif %} disabled>-- Branch --
                            </option>
                            {% for b in branches %}
                            <option value="{{b.branch_code}}" {% ifequal b.branch_code branch %} selected {% endifequal %}>
                                {{b.branch_name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <label style="padding-left:1vh;">Faculty</label>
                    <div class="select-style">
                        <select id="Faculty" name="faculty">
                            <option value="" selected disabled>-- Faculty --</option>
                            <option></option>
                        </select>
                    </div>
                </div>


            </div>
            <div class="col-12 mt-2 text-center">
                <button name="submit" value="faculty" type="submit">Submit</button>
            </div>
        </div>
        <div class="card m-auto" style="width: 80%;margin-top: 50px!important;">
            <!-- <a href="">See All Allotments</a> -->
            <div class="card-body row">
                <div class="col-md-6">
                    <label>Program</label>
                    <div class="select-style">
                
                        <select id="Program" name="program" class="select-style">
                            <option value="Program" {% if batch %} {% else %} selected {% endif %}disabled>-- Program --
                            </option>
                            {% for program in programs %}
                            <option value="{{program.id}}" {% ifequal program.id program %} selected {% endifequal %}>
                                {{program.program_name}}
                            </option>
                            {% endfor %}
                        </select>
                    </div><br>
                </div>
                <div class="col-md-6">
                    <label>Academic Year</label>
                    <div class="select-style">
        
                        <select id="Academic-Year" name="academic-year" class="select-style">
                            <option value="Academic-Year" disabled>-- Academic Year --
                            </option>
                            {% for year in academic_years %}
                            <option value="{{year}}">{{year}}
                            </option>
                            {% endfor %}
                        </select>
                    </div><br>
                </div>
                <div class="col-md-6">
                    <label>Year</label>
                    <div class="select-style">
                
                        <select id="Year" name="year">
                            <option value="Semester" {% if year %} {% else %} selected {% endif %} disabled>-- year --
                            </option>
                            <option value="1" {% ifequal year "1" %} selected {% endifequal %}>1st Year</option>
                            <option value="2" {% ifequal year "2" %} selected {% endifequal %}>2nd Year</option>
                            <option value="3" {% ifequal year "3" %} selected {% endifequal %}>3rd Year</option>
                            <option value="4" {% ifequal year "4" %} selected {% endifequal %}>4th Year</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <br />
                    <label>Semester</label>
                    <div class="select-style">
        
                        <select id="Semester" name="semester">
                            <option value="Semester" {% if semester %} {% else %} selected {% endif %} disabled>--
                                Semester --</option>
                            <option value="1" {% ifequal semester "1" %} selected {% endifequal %}>1 Sem</option>
                            <option value="2" {% ifequal semester "2" %} selected {% endifequal %}>2 Sem</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <label>Branch</label>
                    <div class="select-style">
        
                        <select id="Branch" name="branch" class="select-style">
                            <option value="Branch" {% if branch %} {% else %} selected {% endif %} disabled>-- Branch --
                            </option>
                            {% for b in branches %}
                            <option value="{{b.branch_code}}" {% ifequal b.branch_code branch %} selected {% endifequal %}>
                                {{b.branch_name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                
        
        
            </div>
            <div class="col-12 mt-2 text-center">
                <button name="submit" value="class" type="submit">Submit</button>
            </div>
        </div>
        </div>
    </form>
    </div>
    <div class="toast-container position-fixed p-2" style="top: 2.5rem; right: 2rem;">
        {% if messages %}
        {% for message in messages %}
        <div class="toast toast-stacked fade show" role="alert" aria-live="assertive" aria-atomic="true"
            data-delay="5000" style="border: 2px solid black;">
            <div class="toast-header">
                <strong class="mr-auto">{{message}}</strong>
                <button type="button" class="ml-1 close" data-dismiss="toast" aria-label="Close"
                    onclick="toast_close(this)">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <script>
        var facultyBranchSelect = document.getElementById("Branch");
        var filters = { 'program': '{{program}}', 'branch': '{{branch}}', 'year': '{{year}}', 'semester': '{{semester}}' }
        var facultybranch = '{{faculty_branch}}';
        var faculty = [
            {% for fac in faculties %}
        {
            "id": "{{fac.id}}",
                "first_name": "{{fac.first_name}}",
                    "last_name": "{{fac.last_name}}",
                        "branch": "{{fac.faculty_branch.branch_code}}",
            },
        {% endfor %}
        ];
        function getFaculty(faculty) {
            // console.log(faculty)
            f = []
            for (var i = 0; i < faculty.length; i++) {
                if (faculty[i]['first_name'] != null)
                    f[i] = { 'id': faculty[i]['id'], 'text': faculty[i]['first_name'] + ' ' + faculty[i]['last_name'] }
            }
            // console.log(s)
            return f
        }
        function facultyfilter(data) {
            filteredData = data
            // console.log(filteredData)
            if (facultybranch != '') {
                // console.log(facultybranch)
                filteredData = filteredData.filter(function (fac) {
                    return fac['branch'] == facultybranch;
                });
            }
            return filteredData
        }
        $(document).ready(function () {


            $("#Faculty").select2({
                data: getFaculty(facultyfilter(faculty))
            });
        });
        var $facultyselect = $("#Faculty");
        $('#Branch').bind("change", function (e) {

            if (facultyBranchSelect.value == 'Branch')
                facultybranch = ''
            else
                facultybranch = facultyBranchSelect.value
            setSelect2facultyOptions(getFaculty(facultyfilter(faculty)));
        });
        function setSelect2facultyOptions(data) {
            // console.log(data)
            $facultyselect.select2('destroy').empty().select2({ data: data });
        }
        function toast_close(ele) {
            ele.parentElement.parentElement.style.display = 'none'
        }

    </script>
    <script src="{% static 'app-assets/js/scripts/components/components-bs-toast.js' %}"></script>
</body>


</html>

allotments/templates/Allotments.html
{% load static %}
<html>

<title>Allotments</title>
<script src="{% static 'app-assests\js\core\adminjs.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\core\menu\menu-types\vertical-menu.css'%">

<link rel="stylesheet" type="text/css" href="{% static 'assets\css\style.css'%}">

<link rel="stylesheet" href="{% static 'css\subj.css'%}">
<link rel="stylesheet" media="print" href="(% static 'css\print.css'%}">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta name="description"
    content="Vuexy admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
<meta name="keywords"
    content="admin template, Vuexy admin template, dashboard template, flat admin template, responsive admin template, web app">
<meta name="author" content="PIXINVENT">

<link rel="apple-touch-icon" href="{% static 'app-assets\images\ico\apple-icon-120.png'%}">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'app-assets\images\ico\favicon.ico'%}">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600"
    rel="stylesheet">

<!-- BEGIN: Vendor CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'app-assets\vendors\css\vendors.min.css'%}">
<!-- END: Vendor CSS-->

<!-- BEGIN: Theme CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\bootstrap.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\bootstrap-extended.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\colors.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\components.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\themes\dark-layout.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\themes\bordered-layout.css'%}">

<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'app-assets\css\core\menu\menu-types\vertical-menu.css'%}">
<!-- END: Page CSS-->

<!-- BEGIN: Custom CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'assets\css\style.css'%}">
<!-- END: Custom CSS-->
<link rel="stylesheet" media="print" href="{% static 'css\print.css'%}">

</head>

<body>
    <div class="topnav" id="myTopnav" class="show">

        <a href="{% url 'allotments:allotments' %}" class="active">Allotments</a>
        <a href="{% url 'allotments:new-allotment' %}">New Allotment</a>

        <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
    </div>

    <br><br>
    <h3 class="text-center" style="font-family:Georgia, 'Times New Roman', Times, serif;font-weight:bold;color:black;">
        {% ifequal type "faculty" %}
       {{faculty.first_name}} {{faculty.last_name}} - 
       {{branch.branch_name}} 
       {% endifequal %} 
       <button type="button" class="btn print-hide"
            onclick="window.print()"><img src="{%static 'assets\printer.png'%}" /></button></h3>
    <center>
        <table border="1" id="edit"
            style="font-weight:bold;font-family:Georgia, 'Times New Roman', Times, serif;color:black;background-color:blanchedalmond">
            <tr style="height:20px;">
                <th>NO.</th>
                <th>Program</th>
                <th>Batch</th>
                <th>Branch</th>
                <th>Year</th>
                <th>Semester</th>
                <th>Subject Code</th>
                <th>Subject</th>
                {% ifequal type "class" %}
                <th>Faculty</th>
                {% endifequal %}
                <!-- <th>Attendance status</th>
                <th>Marks status</th> -->
            </tr>

            {% for allotment in allotments %}
            <tr>
                <th>{{forloop.counter}} . </th>
                <th>{{allotment.subject.program.program_name}}</th>
                <th>{{allotment.batch.batch_name}}</th>
                <th>{{allotment.branch.branch_name}}</th>
                <th>{{allotment.subject.year}}</th>
                <th>{{allotment.subject.semester}}</th>
                <th>{{allotment.subject.subject_code}}</th>
                <th>{{allotment.subject.subject_name}}</th>
                {% ifequal type "class" %}
                <th>{{allotment.faculty.first_name}} {{allotment.faculty.last_name}}</th>
                {% endifequal %}
            </tr>
            {% endfor %}
        </table>
    </center><br>

    <div class="toast-container position-fixed p-2" style="top: .5rem; right: 2rem;" id="toast-container">
        {% if messages %}
        {% for message in messages %}
        <div class="toast toast-stacked fade show" role="alert" aria-live="assertive" aria-atomic="true"
            data-delay="5000" style="border: 2px solid black;">
            <div class="toast-header">
                <strong class="mr-auto">{{message}}</strong>
                <button type="button" class="ml-1 close" data-dismiss="toast" aria-label="Close"
                    onclick="toast_close(this)">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <!--<script>
        const table = document.getElementById("marks");
        const edit_button = document.getElementById("edit-button");
        edit_button.addEventListener("click", function () {
            table.contentEditable = true;
            table.style.backgroundColor = "white";
        });
    </script>-->
    <script src="{% static 'app-assets\vendors\js\vendors.min.js' %}"></script>
    <script src="{% static 'app-assets\js\core\app-menu.js' %}"></script>
    <script src="{% static 'app-assets\js\core\app.js' %}"></script>
    <script src="{% static 'app-assets\js\scripts\components\components-modals.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script>
        $(window).on('load', function () {
            if (feather) {
                feather.replace({
                    width: 14,
                    height: 14
                });
            }
        })
        function toast_close(ele) {
            ele.parentElement.parentElement.style.display = 'none'
        }
    </script>
    <script src="{% static 'app-assets/js/scripts/components/components-bs-toast.js' %}"></script>
</body>

</html>